# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servicewithmetrics.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'servicewithmetrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18servicewithmetrics.proto\"\x16\n\x05Thing\x12\r\n\x05value\x18\x01 \x01(\x03\x32\x31\n\x12ServiceWithMetrics\x12\x1b\n\x07\x44oThing\x12\x06.Thing\x1a\x06.Thing\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicewithmetrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THING']._serialized_start=28
  _globals['_THING']._serialized_end=50
  _globals['_SERVICEWITHMETRICS']._serialized_start=52
  _globals['_SERVICEWITHMETRICS']._serialized_end=101
# @@protoc_insertion_point(module_scope)
