# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRange = channel.unary_stream(
                '/Streaming/GetRange',
                request_serializer=streaming__pb2.GetRangeRequest.SerializeToString,
                response_deserializer=streaming__pb2.GetRangeResponse.FromString,
                _registered_method=True)
        self.SumNumbers = channel.stream_unary(
                '/Streaming/SumNumbers',
                request_serializer=streaming__pb2.SumNumbersRequest.SerializeToString,
                response_deserializer=streaming__pb2.SumNumbersResponse.FromString,
                _registered_method=True)
        self.DoubleNumbers = channel.stream_stream(
                '/Streaming/DoubleNumbers',
                request_serializer=streaming__pb2.DoubleNumber.SerializeToString,
                response_deserializer=streaming__pb2.DoubleNumber.FromString,
                _registered_method=True)


class StreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SumNumbers(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoubleNumbers(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRange': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRange,
                    request_deserializer=streaming__pb2.GetRangeRequest.FromString,
                    response_serializer=streaming__pb2.GetRangeResponse.SerializeToString,
            ),
            'SumNumbers': grpc.stream_unary_rpc_method_handler(
                    servicer.SumNumbers,
                    request_deserializer=streaming__pb2.SumNumbersRequest.FromString,
                    response_serializer=streaming__pb2.SumNumbersResponse.SerializeToString,
            ),
            'DoubleNumbers': grpc.stream_stream_rpc_method_handler(
                    servicer.DoubleNumbers,
                    request_deserializer=streaming__pb2.DoubleNumber.FromString,
                    response_serializer=streaming__pb2.DoubleNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Streaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Streaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Streaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Streaming/GetRange',
            streaming__pb2.GetRangeRequest.SerializeToString,
            streaming__pb2.GetRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SumNumbers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Streaming/SumNumbers',
            streaming__pb2.SumNumbersRequest.SerializeToString,
            streaming__pb2.SumNumbersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoubleNumbers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/Streaming/DoubleNumbers',
            streaming__pb2.DoubleNumber.SerializeToString,
            streaming__pb2.DoubleNumber.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
